# directories and paths
root_dir: '${hydra:runtime.cwd}'
dataset_name: 'helsinki_selected'
indir: '${root_dir}/dataset/${dataset_name}'
outdir: 'model-${model_name}_dataset-${dataset_name}'
modeldir: '${root_dir}/points2surf/models'
models: '${model_name}'
dataset: '${indir}/testset.txt'
model_name: 'helsinki_fullview'
modelpostfix: '_400.pth'
complexes_path: null
dataset_paths: '${root_dir}/dataset/${dataset_name}/06_vertex_group/*.vg'
result_dir: '${outdir}/reconstructed'  # change accordingly
gt_dir: '${root_dir}/dataset/${dataset_name}/03_meshes'

# abspy settings
normalise: false
append_bottom: false
prioritise_verticals: true
coefficient: 0.0010
refine_epsilon: 0.005
refine_theta: 0.1745  # 10 * 3.1416 / 180

# points2surf settings
seed: 40938661
batchSize: 201
workers: 8
cache_capacity: 1
query_grid_resolution: 256
epsilon: 3
certainty_threshold: 13
sigma: 5
gpu_idx: 0
parampostfix: '_params.pth'
sampling: 'full'
reconstruction: false
eval_samples: 10000
eval_csv: 'hausdorff_dist_pred_rec.csv'

# hydra settings
override hydra/job_logging: colorlog
override hydra/hydra_logging: colorlog
