# directories and paths
root_dir: '${hydra:runtime.cwd}'
indir: '${root_dir}/datasets/${dataset_name}'
outdir: '${root_dir}/outputs/${dataset_name}'
modeldir: '${root_dir}/models'
models: '${model_name}'
model_name: 'helsinki_fullview'
modelpostfix: '_model.pth'
complexes_path: null
datadir: '${root_dir}/datasets'
dataset_name: 'helsinki_mini'
dataset: '${indir}/testset.txt'
dataset_paths: '${root_dir}/datasets/${dataset_name}/06_vertex_group/*.vg'
result_dir: '${outdir}/reconstructed'
gt_dir: '${root_dir}/datasets/${dataset_name}/03_meshes'

# download settings
url_datasets: {'helsinki_mini': 'https://drive.google.com/uc?export=download&id=1mzbNNrGtbbbu7-mG2FrRRRdDZ9P5jDDK'}
url_models: {'helsinki_fullview': 'https://drive.google.com/uc?export=download&id=1t1yQ7b0mME6EBlEa1CLAHJC_pcKQxZkW'}

# abspy settings
normalise: false
append_bottom: false
prioritise_verticals: false
coefficient: 0.0010
refine_epsilon: 0.005
refine_theta: 0.1745  # 10 * 3.1416 / 180

# points2surf settings
seed: 40938661
batchSize: 201
workers: 8
cache_capacity: 1
query_grid_resolution: 256
epsilon: 3
certainty_threshold: 13
sigma: 5
gpu_idx: [0]  # set < 0 to use CPU
parampostfix: '_params.pth'
sampling: 'full'
reconstruction: false
eval_samples: 10000
eval_csv: 'hausdorff_dist_pred_rec.csv'

# hydra settings
hydra:
  run:
    dir: '${outdir}'
  verbose: false
defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
